// <auto-generated />
namespace JobbyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Jobby6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Jobby6));
        
        string IMigrationMetadata.Id
        {
            get { return "201904031405062_Jobby6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
